[package]
name = "gillnet-gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.15.0"
actix-web-lab = "0.27.0"
awc = "3.8.2"
bytes = "1.12.1"
futures-util = "0.3.34"
regex = "1.13.1"
serde = { version = "1.0.229", features = ["derive"] }
yaml_serde = "0.10.7"
