[[plugins]]
name = "my-oauth-plugin"
type = "oauth2-plugin"
base-url = "$MY_OAUTH_BASE_URL"
client-id = "$MY_OAUTH_CLIENT_ID"
client-secret = "$MY_OAUTH_CLIENT_SECRET"

[[plugins]]
name = "my-token-plugin"
type = "token-plugin"
keys = ["api-key"]
tokens = ["$MY_TOKEN"]