# plugins:

# - name: my-oauth-plugin
#   type: oauth2-plugin
#   params:
#     base-url: $MY_OAUTH_BASE_URL
#     client-id: $MY_OAUTH_CLIENT_ID
#     client-secret: $MY_OAUTH_CLIENT_SECRET

# - name: my-token-plugin
#   type: token-plugin
#   params:
#     keys: [api-key]
#     tokens: [ $MY_TOKEN ]

# services:
#   - name: my-token-svc
#     url: "http://my-token-application-svc.local:8080"

#   - name: my-application-svc
#     url: "http://my-application-svc.local:8080"

routes:
  - name: ui-route
    url: "http://my-application-ui.local:8080"
    paths: [/index, /home, /landing]
    strip-path: true

  - name: tkn-svc-route
    url: my-token-svc
    paths: [/check]
    strip-path: true
    plugins:
      - name: my-token-plugin

  - name: my-application-svc-route
    url: my-application-svc
    paths: ["/svc"]
    match-type: PREFIX

  - name: my-application-svc-user-route
    url: my-application-svc
    paths: [/svc/user]
    plugins:
      - name: my-oauth-plugin
        params:
          roles: [user, admin]

  - name: my-application-svc-admin-route
    url: my-application-svc
    paths: [/svc/admin]
    plugins:
      - name: my-oauth-plugin
        params:
          roles: [admin]
          insert-headers: 
            "USER-ID": "{user-id}"
            "USER-EMAIL": "{user-email}"
          